specific_titles = ("FORMER U.S. PRESIDENT", "FMR. PRESIDENT", "PRESIDENT OF THE UNITED STATE",
                   "PRESIDENT OF THE UNITED STATES", "VICE PRESIDENT-ELECT",
                   "GERMAN CHANCELLOR",
                 "PRESIDENT-ELECT", "FORMER GOV.", "FMR. JUSTICE",
                 "1ST LT.", "2ND LT.", "2ND. LT.", "UTAH REP.", "1ST CLASS",
                 "FORMER U.S. AMBASSADOR TO VIETNAM", "FORMER U.S. CONGRESSWOMAN",
                   "INDEPENDENT SENATOR",
                   "OF VERMONT", "OF NEBRASKA", "OF PENNSYLVANIA", "OF OHIO",
                   "OF INDIANA", "OF ARIZONA", "OF TEXAS", "OF ALABAMA",
                   "OF WISCONSIN", "OF COLORADO", "OF OREGON", "OF ILLINOIS",
                   "OF DETROIT", "OF CONNECTICUT", "OF NEW MEXICO", "OF CALIFORNIA",
                   "ON CHINA", " AS LBJ",
                   "STAFF SGT.",
                   "NAVY CAPTAIN",
                   "SOLICITOR GENERAL",
                   "POSTMASTER GENERAL",
                   "SENATE MAJORITY LEADER",
                   "SERGEANT MAJOR",
                   "DETECTIVE SUPERINTENDENT",
                   "NATO SECRETARY-GENERAL",
                   "MAJOR GENERAL",
                   "INSPECTOR GENERAL",
                   "GOVERNOR GENERAL",
                   "BRIGADE COMMANDER",
                   "CHIEF WARRANT",
                   "FIRE CHIEF",
                   "AIR CHIEF",
                   "ASSISTANT CHIEF",
                   "CHIEF JUSTICE",
                   "CHIEF PETTY",
                   "OAK CREEK POLICE CHIEF",
                   "POLICE CHIEF ",
                   "SENIOR CHIEF",
                   "REAR ADMIRAL",
                   "STATE REP.",
                   "STATE SENATOR",
                   "STATE SEN.",
                   "STAFF MAJ.",
                   "RECOLOGY’S",
                   "PENNSYLVANIA STATE POLICE",
                   "NORTH TOWER OFFICE WORKER",
                   "COLORADO DEMOCRAT",
                   "NEW YORK CITY",
                   "PARTNERSHIP DIRECTOR",
                   "WASHINGTON POST FILM CRITIC",
                   "(D) WASHINGTON",
                   "LANCE CPL.",
                   "STATE ADJUTANT GENERAL",
                   "HOUSE FREEDOM CAUCUS",
                   "FORMER SUPREME COURT JUSTICE", "WHITE HOUSE PRESS SECRETARY",
                   "WHITE HOUSE BUDGET DIRECTOR",
                 "AMBASSADOR TO THE UNITED NATIONS",
                   "SECRETARY OF VETERANS AFFAIRS",
                   "NORTHWESTERN UNIVERSITY FINANCE PROFESSOR",
                   "RADIO IOWA REPORTER",  "SECRETARY OF STATE",
                   "SECURETARY OF STATE",
                 "U.S. AMBASSADOR TO THE U.N.", "U.S. ENERGY SECRETARY",
                 "U.S. TREASURY SECRETARY", "U.S. REPRESENTATIVE",
                 "SECRETARY OF HEALTH AND HUMAN SERVICES", "NEW YORK CITY POLICE COMMISSIONER",
                 "LOS ANGELES CLIPPERS POINT", "FBI SPECIAL AGENT IN CHARGE",
                 "CHIEF OF MILITARY INTELLIGENCE", "SENATE FOREIGN RELATIONS COMMITTEE",
                   "MINISTER OF AGRICULTURE", "FBI DIRECTOR",
                   "HOUSE MAJORITY LEADER",
                   "SECRETARY OF DEFNESE",
                   "HOUSE MINORITY LEADER",
                   "HOUSE MINORITY WHIP",
                   "WHITE HOUSE SPOKESMAN",
                   "HOUSE SPEAKER",
                   "SEC. OF STATE",
                   "STATE DEPARTMENT SPOKESWOMAN",
                   "STATE DEPARTMENT SPOKESMAN",
                   "ASSISTANT ATTORNEY GENERAL",
                   "BISHOP",
                   "FIRST LADY",
                   "HIGHWAY PATROL CAPTAIN",
                   "MEXICAN FINANCE SECRETARY",
                   "NPR TV CRITIC",
                   "CITY COUNCILLOR",
                   "REPORTER AND AUTHOR",
                   "RUSSIAN FOREIGN MINISTER",
                   "SECRETARY OF TRANSPORTATION",
                   "SECRETARY OF TREASURY",
                   "TWOTIME OLYMPIC GOLD MEDALIST",
                   "SECRETARY OF HOMELAND SECURITY",
                   "SECURITY OF HOMELAND SECURITY",
                   "SOUTH CAROLINA CONGRESSMAN",
                   "SOUTH CAROLINA SENATOR",
                   "MIAMI HEAT FORWARD",
                   "CHIEF OPERATING",
                   "FOR MITT ROMNEY",
                   "CHINESE FOREIGN MINISTER",
                   "– FOREIGN CORRESPONDENT",
                   "STANFORD BIOENGINEERING PROFESSOR",
                   "STANFORD UNIVERSITY PROFESSOR",
                   "SECRETARY OF DEFENSE",
                   "ACCUWEATHER METEOROLOGIST",
                   "UBER SPOKESPERSON",
                   "INTERIOR SECRETARY",
                   'JACKIE RYAN OFFERED THIS',
                   "FED CHAIR",
                   "CARDOZO LAW SCHOOL PROFESSOR",
                   "ATTORNEY GENERAL",
                   "WYOMING SENATOR",
                   "PROJECT MANAGER",
                   "OF THE SHERIFF’S OFFICE",
                   "MAJORITY WHIP",
                   "PUERTO RICO GOVERNOR",
                   "ILLINOIS DEMOCRAT",
                   "ILLINOIS DEMOCRAT",
                   "SECRETARY OF EDUCATION",
                   "NATO SECRETARYGENERAL",
                   "NINETEENYEAROLD",
                   "SPEAKER OF THE HOUSE",
                   "ACTING UKRAINIAN",
                   "UTAH STATE",
                   "WALL STREET JOURNAL REPORTER",
                   "DEMOCRATIC PRESIDENTIAL CANDIDATE",
                   "FINANCIAL TIMES ARCHITECTURE CRITIC",
                   "FULTON COUNTY DISTRICT ATTORNEY",
                   "GOVERNING SOCIALIST PARTY SPOKESPERSON",
                   "RADIO IOWA’S",
                   "UNITED STATES AMBASSADOR",
                   "SAINT LOUIS COUNTY POLICE CHIEF",
                   "POLICE COMMISSIONER",
                   "STATE WATER BOARD CHAIR",
                   "HOMELAND SECURITY SECRETARY",
                   "OF THE DAILY BEAST",
                   "UNIVERSITY OF AKRON ECONOMIST",
                   "CHINESE FOREIGN MINISTRY SPOKESWOMAN",
                   "HARVARD BUSINESS SCHOOL PROFESSOR",
                   "PUERTO RICO GOVERNOR",
                   "HEAD OF U.S. BOND TRADING",
                   "NATIONAL SECURITY ADVISOR",
                 "UNIVERSITY OF CENTRAL FLORIDA’S PRESIDENT", "SECRETARY OF VETERANS AFFAIRS RETIRED",
                  "HOUSING AND URBAN DEVELOPMENT SECRETARY", "HEALTH AND HUMAN SERVICES SECRETARY",
                  "BRITISH FOREIGN SECRETARY", "BRITISH PRIME MINISTER",
                  "CHIEF MASTER", "DALLAS POLICE CHIEF", "COUNTY SCHOOL ADMINISTRATOR",
                  "E.U. COMPETITION COMMISSIONER", "FACEBOOK GENERAL COUNSEL", "EXECUTIVE VICE",
                  "OF AMNESTY INTERNATIONAL", "GM VICE", "GREEN PARTY CANDIDATE")
