titles = ("PRESIDENT", "PRESDIENT", "PRESIDEDNT", "PRESIENT", "PRESIDNENT",
          "PRIME MINISTER", "MAYOR", "VICE  ",
          "CHANCELLOR", "DEPARTMENT SPOKESMAN",
          "U.S. ATTORNEY GENERAL", "U.S AMBASSADOR",
          "U.N. AMBASSADOR", "MEDAL OF HONOR RECIPIENT",
          "LT.", "COLONEL", "COL.", "SGT.", "CAPT.", "GEN.",
          "ADM.", "VICE ADM.", "COM.", "MAJ.", "BRIG.", "CPL.",
          "(USGS)", "LIEUTENANT", "MEXICAN", "COMMANDER",
          "U.S. ARMY", "U.S.", "U. S.", "U.S",
          "R- WIS.", "MASSACHUSETTS", "MASS.",
          "MISSISSIPPI", "JAPANESE", "SOUTH DAKOTA",
          "NORTH DAKOTA", "TEXAS STATE", "TREASURY SECRETARY",
          "SECRETARY-GENERAL", "MAJORITY LEADER",
          "ARIZONA", "NEW YORK", "ICONN.", "RWIS.",
          "MINNESOTA", "1ST", "REPRESENTATIVE",
          "HUDSON INSTITUTE",
          "GOV.", "REP.", "SEN.", "REPUBLICAN", "DEMOCRAT",
          "SENATOR", "CALIFORNIA’S", "CALIFORNIA",
          "DEMOCRATIC", "COMMITTEE", "CONGRESSMAN", "AUSTRALIAN",
          "CHAIRMAN", "OFFICER", "JUDGE", "FATHER",
          "REV.", "DR.", "PROF.", "FMR.", "FORMER", "RETIRED",
          "SPC.", "SEC.", "DEL.", "DEPUTY", "ADMIRAL",
          "RET.", "FILM CRITIC", "OF PACIFICA RADIO",
          "ACTING", "IC SENATOR")
